name: CI Pipeline
on:
  pull_request:
    types: [opened, edited, reopened, synchronize, review_requested]
    branches:
      - develop

  pull_request_review:
    types: [submitted]  # Це працює, якщо хочеш перевіряти, чи було подано рецензію

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run tests
        run: pytest --junitxml=report.xml

  review-check:
    runs-on: windows-latest  
    steps:
        - name: Code Review Check for develop
          uses: actions/github-script@v6
          with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           script: |
            const prNumber = context.payload.pull_request?.number;
            if (!prNumber) {
              core.setFailed("Не вдалося отримати номер PR");
              return;
            }
      
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
      
            console.log("Reviews:", reviews);
      
            const approved = reviews.some(review => review.state === 'APPROVED');
      
            if (!approved) {
              core.setFailed("Код-рев’ю не схвалено. Список рецензій: " + JSON.stringify(reviews, null, 2));
            }
      
  analysis:
    runs-on: windows-latest  
    needs: review-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count lines of code with Cloc
        run: |
          choco install cloc
          cloc src/ > cloc-report.txt
          cat cloc-report.txt

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-windows.zip -o sonar-scanner.zip
          powershell -Command "Expand-Archive -Path sonar-scanner.zip -DestinationPath sonar-scanner"
          $env:PATH += ";$(pwd)\sonar-scanner\sonar-scanner-4.8.0.2856-windows\bin"
          sonar-scanner \
            -Dsonar.projectKey= \
            -Dsonar.organization=my-org \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$env:SONAR_TOKEN

      - name: Запуск flake8 через Reviewdog
        uses: reviewdog/action-flake8@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      - name: Запуск Black через Reviewdog
        uses: reviewdog/action-black@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: info
